- id: doi:10.6019/TOL.pangenome-graphs-w.2025.00001.1
  authors:
  - Samuel T. Horsfield
- id: doi:10.1101/2025.03.23.644600
  title: Unlocking CRISPR-Cas9 editing for widely diverse Dictyostelid species
  authors:
  - Mireia Garriga-Canut
  - Nikki Cannon
  - Matthew Benton
  - Andrea Zanon
  - Samuel T Horsfield
  - Jacob Scheurich
  - Kim Remans
  - John Lees
  - Alexandre Paix
  - Jordi van Gestel
  publisher: Molecular Systems Biology 
  date: '2026-01-12'
  link: https://link.springer.com/article/10.1038/s44320-025-00180-8