- id: doi:10.6019/TOL.pangenome-graphs-w.2025.00001.1
  authors:
  - Samuel T. Horsfield
- id: doi:10.1101/2025.03.18.643841
  title: Pore-C sequencing identifies episome-driven chromosome conformation perturbations differentiating pneumococcal epigenetic variants
  publisher: PLOS Pathogens
  date: '2025-08-14'
  link: https://doi.org/10.1371/journal.ppat.1013392
- id: doi:10.1101/2023.01.24.524926
  title: Accurate and fast graph-based pangenome annotation and clustering with ggCaller
  authors:
  - Samuel T. Horsfield
  - Gerry Tonkin-Hill
  - Nicholas J. Croucher
  - John A. Lees
  publisher: Genome Research
  date: '2023-08-24'
  link: https://genome.cshlp.org/content/33/9/1622